# Step-by-step explanation of kernel computation

In [1]:
import numpy as np
X = np.random.rand(3,2)
X

array([[0.33689323, 0.26565359],
       [0.22579323, 0.91294533],
       [0.05396156, 0.10009886]])

We have a 3x2 matrix X and we want to compute the differences between each row of X and all the other rows of X. So we want to obtain a 3x3x2 tensor T in which T[i] is the matrix X[i] - X. Notice that X[i] is a vector (1x2), whereas X is a matrix (3x2). Numpy handles the difference in shapes by broadcasting X[i] to a 3x2 matrix in which each row is a copy of X[i]. Therefore, T[1] would be:

In [16]:
X[1] - X

array([[ 0.68236623,  0.21782958],
       [ 0.        ,  0.        ],
       [ 0.23592784, -0.43669585]])

To perform this operation, we first transform X into a 3x1x2 tensor N by adding a new axis:

In [14]:
N = X[:,np.newaxis,:]
print(N.shape)
N

(3, 1, 2)


array([[[0.2182524 , 0.15390302]],

       [[0.90061862, 0.3717326 ]],

       [[0.66469078, 0.80842845]]])

Now we exploit numpy broadcasting to compute N - X, obtaining the 3x3x2 tensor T we were looking for. N is a 3x1x2 tensor and X is a 3x2 matrix. To perform this operation, both N and X are broadcasted into a 3x3x2 tensor.

In [18]:
np.broadcast_to(N, (3,3,2)) - np.broadcast_to(X, (3,3,2))

array([[[ 0.        ,  0.        ],
        [-0.68236623, -0.21782958],
        [-0.44643838, -0.65452543]],

       [[ 0.68236623,  0.21782958],
        [ 0.        ,  0.        ],
        [ 0.23592784, -0.43669585]],

       [[ 0.44643838,  0.65452543],
        [-0.23592784,  0.43669585],
        [ 0.        ,  0.        ]]])

In [19]:
T = N - X
T

array([[[ 0.        ,  0.        ],
        [-0.68236623, -0.21782958],
        [-0.44643838, -0.65452543]],

       [[ 0.68236623,  0.21782958],
        [ 0.        ,  0.        ],
        [ 0.23592784, -0.43669585]],

       [[ 0.44643838,  0.65452543],
        [-0.23592784,  0.43669585],
        [ 0.        ,  0.        ]]])

# Sparse matrix

In [36]:
import numpy as np
from numpy.random import default_rng

Test

In [55]:
X = np.random.rand(8000,700)
Y = np.random.randint(2, size=8000)
K = np.random.rand(8000,8000)
X.shape, Y.shape, K.shape

((8000, 700), (8000,), (8000, 8000))

Classic

In [57]:
alphas = np.zeros(X.shape[0])
rng = default_rng(42)
l = 0.5

for t in range(1,10000):
    i = rng.integers(X.shape[0])
    s = np.sum(
        [alphas[j] * Y[j] * K[i,j] 
            for j in range(X.shape[0])])
    if (Y[i] / (l * t)) * s < 1:
        alphas[i] += 1

With matrices

In [58]:
alphas2 = np.zeros(X.shape[0])
rng = default_rng(42)
l = 0.5

for t in range(1,10000):
    i = rng.integers(X.shape[0])
    s = alphas2.dot((Y * K[i]))
    if (Y[i] / (l * t)) * s < 1:
        alphas2[i] += 1

In [59]:
np.all(alphas == alphas2)

True