# Step-by-step explanation of kernel computation

In [6]:
import numpy as np
X = np.random.rand(3,2)
X

array([[0.2182524 , 0.15390302],
       [0.90061862, 0.3717326 ],
       [0.66469078, 0.80842845]])

We have a 3x2 matrix X and we want to compute the differences between each row of X and all the other rows of X. So we want to obtain a 3x3x2 tensor T in which T[i] is the matrix X[i] - X. Notice that X[i] is a vector (1x2), whereas X is a matrix (3x2). Numpy handles the difference in shapes by broadcasting X[i] to a 3x2 matrix in which each row is a copy of X[i]. Therefore, T[1] would be:

In [16]:
X[1] - X

array([[ 0.68236623,  0.21782958],
       [ 0.        ,  0.        ],
       [ 0.23592784, -0.43669585]])

To perform this operation, we first transform X into a 3x1x2 tensor N by adding a new axis:

In [14]:
N = X[:,np.newaxis,:]
print(N.shape)
N

(3, 1, 2)


array([[[0.2182524 , 0.15390302]],

       [[0.90061862, 0.3717326 ]],

       [[0.66469078, 0.80842845]]])

Now we exploit numpy broadcasting to compute N - X, obtaining the 3x3x2 tensor T we were looking for. N is a 3x1x2 tensor and X is a 3x2 matrix. To perform this operation, both N and X are broadcasted into a 3x3x2 tensor.

In [18]:
np.broadcast_to(N, (3,3,2)) - np.broadcast_to(X, (3,3,2))

array([[[ 0.        ,  0.        ],
        [-0.68236623, -0.21782958],
        [-0.44643838, -0.65452543]],

       [[ 0.68236623,  0.21782958],
        [ 0.        ,  0.        ],
        [ 0.23592784, -0.43669585]],

       [[ 0.44643838,  0.65452543],
        [-0.23592784,  0.43669585],
        [ 0.        ,  0.        ]]])

In [19]:
T = N - X
T

array([[[ 0.        ,  0.        ],
        [-0.68236623, -0.21782958],
        [-0.44643838, -0.65452543]],

       [[ 0.68236623,  0.21782958],
        [ 0.        ,  0.        ],
        [ 0.23592784, -0.43669585]],

       [[ 0.44643838,  0.65452543],
        [-0.23592784,  0.43669585],
        [ 0.        ,  0.        ]]])

In [27]:
X = np.random.rand(1000,100)

In [28]:
from smml.kernel import GaussianKernel
res1 = np.zeros((X.shape[0],X.shape[0]))
K = GaussianKernel()

for i in range(0,X.shape[0]):
    for j in range(0,X.shape[0]):
        res1[i,j] = K(X[i], X[j])

res1

array([[1.00000000e+00, 5.32465931e-16, 3.06394189e-14, ...,
        1.33469647e-14, 5.94439022e-16, 9.27192292e-17],
       [5.32465931e-16, 1.00000000e+00, 1.61049937e-16, ...,
        4.83467250e-15, 4.18054463e-11, 1.05222056e-14],
       [3.06394189e-14, 1.61049937e-16, 1.00000000e+00, ...,
        1.95036905e-14, 6.57084845e-14, 2.70585445e-15],
       ...,
       [1.33469647e-14, 4.83467250e-15, 1.95036905e-14, ...,
        1.00000000e+00, 1.02042856e-13, 5.66330488e-17],
       [5.94439022e-16, 4.18054463e-11, 6.57084845e-14, ...,
        1.02042856e-13, 1.00000000e+00, 8.08562214e-11],
       [9.27192292e-17, 1.05222056e-14, 2.70585445e-15, ...,
        5.66330488e-17, 8.08562214e-11, 1.00000000e+00]])

In [30]:
np.exp(-(np.linalg.norm(X[:,np.newaxis,:] - X, axis=-1) ** 2) / (2 * 0.25))

array([[1.00000000e+00, 5.32465931e-16, 3.06394189e-14, ...,
        1.33469647e-14, 5.94439022e-16, 9.27192292e-17],
       [5.32465931e-16, 1.00000000e+00, 1.61049937e-16, ...,
        4.83467250e-15, 4.18054463e-11, 1.05222056e-14],
       [3.06394189e-14, 1.61049937e-16, 1.00000000e+00, ...,
        1.95036905e-14, 6.57084845e-14, 2.70585445e-15],
       ...,
       [1.33469647e-14, 4.83467250e-15, 1.95036905e-14, ...,
        1.00000000e+00, 1.02042856e-13, 5.66330488e-17],
       [5.94439022e-16, 4.18054463e-11, 6.57084845e-14, ...,
        1.02042856e-13, 1.00000000e+00, 8.08562214e-11],
       [9.27192292e-17, 1.05222056e-14, 2.70585445e-15, ...,
        5.66330488e-17, 8.08562214e-11, 1.00000000e+00]])